---

- name: Web server group
  hosts: web_servers
  become: yes
  tasks:
    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Start Service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: copy file
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/
        backup: yes
 
- name: Database server group
  hosts: db_servers
  become: yes
  tasks:
    - name: Install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: Start mariadb service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

