---
# tasks file for post-install
- name: install ntp in CentOS
  yum:
    name: "{{item}}"
    state: present
  when: ansible_distribution == "CentOS"
  loop:
    - chrony
    - git
    - zip
    - unzip
    - wget
- name: install ntp in Ubuntu
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  loop:
    - ntp
    - git
    - zip
    - unzip
    - wget

- name: start service in CentOS
  service:
    name: chronyd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: start service in Ubuntu
  service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"
- name: banner file
  copy:
    content: "This content is managed by Ansible - dont change it"
    dest: /etc/motd

- name: copy file with template CentOS
  template:
    src: ntpconf_centos.j2
    dest: /etc/chrony.conf
    backup: yes
  when: ansible_distribution == "CentOS"
  notify:
    - restart service in CentOS

- name: copy file with template Ubuntu
  template:
    src: ntpconf_ubuntu.j2
    dest: /etc/ntp.conf
    backup: yes
  when: ansible_distribution == "Ubuntu"
  notify:
    - restart service in Ubuntu

- name: copy file
  copy:
    src: test.txt
    dest: /tmp/test.txt
